<template>
  <div class="loadingio-spinner-dual-ball-87eeilkrd7b">
    <div class="ldio-r95l2kqr0vp">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<style>
@keyframes ldio-r95l2kqr0vp-o {
  0% {
    opacity: 1;
    transform: translate(0 0);
  }
  49.99% {
    opacity: 1;
    transform: translate(40px, 0);
  }
  50% {
    opacity: 0;
    transform: translate(40px, 0);
  }
  100% {
    opacity: 0;
    transform: translate(0, 0);
  }
}
@keyframes ldio-r95l2kqr0vp {
  0% {
    transform: translate(0, 0);
  }
  50% {
    transform: translate(40px, 0);
  }
  100% {
    transform: translate(0, 0);
  }
}
.ldio-r95l2kqr0vp div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  top: 80px;
  left: 60px;
}
.ldio-r95l2kqr0vp div:nth-child(1) {
  background: var(--text-primary);
  animation: ldio-r95l2kqr0vp 1s linear infinite;
  animation-delay: -0.5s;
}
.ldio-r95l2kqr0vp div:nth-child(2) {
  background: var(--text-secondary);
  animation: ldio-r95l2kqr0vp 1s linear infinite;
  animation-delay: 0s;
}
.ldio-r95l2kqr0vp div:nth-child(3) {
  background: var(--text-primary);
  animation: ldio-r95l2kqr0vp-o 1s linear infinite;
  animation-delay: -0.5s;
}
.loadingio-spinner-dual-ball-87eeilkrd7b {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
  transform: scale(0.5);
}
.ldio-r95l2kqr0vp {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-r95l2kqr0vp div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
